<?php
declare(strict_types=1);

use Yireo\LokiCheckoutMollie\Magewire\Checkout\Payment\Method\Creditcard;

/** @var Creditcard $magewire */
?>
<div>
    <div id="<?= $magewire->getJsName() ?>"></div>
    <script>
        (() => {
            let mollie;

            async function renderMollieComponents() {
                mollie = await Mollie('<?= $magewire->getProfileId() ?>', {
                    locale: '<?= $magewire->getLocale() ?>',
                    testmode: <?= $magewire->isTestMode() ? 'true' : 'false' ?>,
                });

                let cardComponent = mollie.createComponent('card', {
                    styles: {
                        base: {
                            border: '1px solid #000',
                        },
                        invalid: {
                            color: '#dc2626',
                        }
                    }
                });

                cardComponent.mount('#<?= $magewire->getJsName() ?>');
            }

            window.addEventListener('checkout:payment:method-activate', event => {
                if (event.detail.method !== 'mollie_methods_creditcard') {
                    return;
                }

                // @todo: let {token, error} = await mollie.createToken();
                // @todo: Add validation based on "error"

            });

            const script = document.createElement('script');
            script.src = 'https://js.mollie.com/v1/mollie.js';
            script.onload = () => renderMollieComponents();
            document.head.append(script);
        })();
    </script>
</div>
