<?php
declare(strict_types=1);

use Yireo\LokiCheckoutMollie\Magewire\Checkout\Payment\Method\Creditcard;

/** @var Creditcard $magewire */
if (false === $magewire->isVisible()) {
    return '<div></div>';
}
?>
<div>
    <div>Card token: <?= $magewire->value ?></div>
    <div id="<?= $magewire->getJsName() ?>"></div>
    <script>
        (function() {
            window.mollie = null;
            function mollieRenderComponents() {
                window.mollie = Mollie('<?= $magewire->getProfileId() ?>', {
                    locale: '<?= $magewire->getLocale() ?>',
                    testmode: <?= $magewire->isTestMode() ? 'true' : 'false' ?>,
                });

                // @todo: Allow for styling this properly
                let cardComponent = window.mollie.createComponent('card', {
                    styles: {
                        base: {
                            lineHeight: '30px',
                            border: '1px solid #000',
                        },
                        invalid: {
                            color: '#dc2626',
                        }
                    }
                });

                cardComponent.mount('#<?= $magewire->getJsName() ?>');
            }

            const script = document.createElement('script');
            script.src = 'https://js.mollie.com/v1/mollie.js';
            script.onload = () => mollieRenderComponents();
            document.head.append(script);
        })();

        LokiCheckoutValidator.rules.mollie_methods_creditcard = function (component) {
            if (!window.mollie) {
                LokiCheckoutMessenger.error('<?= __('Mollie object unavailable') ?>', component);
                return false;
            }

            let token = null;
            let error = null;
            (async function() {
                const result = await window.mollie.createToken();
                console.log('createToken result', result);
                token = result.token;
                error = result.error;
            })();

            if (error) {
                LokiCheckoutMessenger.error('<?= __('Mollie Error') ?>', component, error);
                return false;
            }

            if (!token) {
                LokiCheckoutMessenger.error('<?= __('Empty Mollie token') ?>', component);
                return false;
            }

            (async function() {
                await Magewire.find('<?= $magewire->id ?>').call('setValue', token);
            })();

            return true;
        }
    </script>

    <style>
        .mollie-component {
            height: auto !important;
            padding: 3px 5px 3px 8px;
        }
    </style>
</div>
