<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\LokiCheckout\Util\Block\CssClass;
use Yireo\LokiCheckoutMollie\Magewire\Checkout\Payment\Method\Creditcard;

/** @var Creditcard $magewire */
/** @var Template $block */
/** @var CssClass $css */
?>
<div class="<?= $css('') ?>">
    <div id="<?= $magewire->getAlpineComponentName() ?>"></div>
    <script>
        (function () {
            window.mollie = null;
            window.mollieCardComponent = null;

            function mollieRenderComponents() {
                window.mollie = Mollie('<?= $magewire->getProfileId() ?>', {
                    locale: '<?= $magewire->getLocale() ?>',
                    testmode: <?= $magewire->isTestMode() ? 'true' : 'false' ?>,
                });

                // @todo: Allow for styling this properly
                window.mollieCardComponent = window.mollie.createComponent('card', {
                    styles: {
                        base: {
                            lineHeight: '30px',
                            border: '1px solid #000',
                        },
                        invalid: {
                            color: '#dc2626',
                        }
                    }
                });

                window.mollieCardComponent.mount('#<?= $magewire->getAlpineComponentName() ?>');
            }

            const script = document.createElement('script');
            script.src = 'https://js.mollie.com/v1/mollie.js';
            script.onload = () => mollieRenderComponents();
            document.head.append(script);
        })();

        LokiCheckoutValidator.rules.mollie_methods_creditcard = async function (component) {
            if (!window.mollie) {
                LokiCheckoutMessenger.error('<?= __('Mollie object unavailable') ?>', component);
                return false;
            }

            const {token, error} = await window.mollie.createToken();

            if (error) {
                LokiCheckoutMessenger.error('<?= __('Mollie Error') ?>', component, error);
                return false;
            }

            if (!token) {
                LokiCheckoutMessenger.error('<?= __('Empty Mollie token') ?>', component);
                return false;
            }

            (async function () {
                await Magewire.find('<?= $magewire->id ?>').call('setValue', token);
            })();

            return true;
        }
    </script>

    <style>
        .mollie-component {
            height: auto !important;
            padding: 3px 5px 3px 8px;
        }
    </style>
</div>
