<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\LokiComponents\Factory\ViewModelFactory;
use Yireo\LokiCheckout\Util\Block\CssClass;
use Yireo\LokiCheckout\Util\Block\TemplateRenderer;
use Yireo\LokiCheckoutMollie\Magewire\Checkout\Payment\Method\WithIssuer;

/** @var Template $block */
/** @var WithIssuer $magewire */
/** @var ViewModelFactory $viewModelFactory */
/** @var TemplateRenderer $templateRenderer */
/** @var CssClass $css */

$templateRenderer = $viewModelFactory->create(TemplateRenderer::class);
$magewire = $block->getMagewire();
?>
<div
    x-data="LokiCheckoutMollieIssuer"
    x-title="<?= $magewire->getAlpineComponentName() ?>"
    x-init-data='<?= $magewire->getAlpineDataAsJson() ?>'
    class="<?= $css('') ?>">
    <?php if ($magewire->issuers): ?>
        <?= $templateRenderer->html($magewire->getChildTemplate(), $block, [
            'alias' => 'issuers',
            'issuers' => $magewire->issuers,
        ]) ?>
    <?php else: ?>
        <span><?= __('No issuers found') ?></span>
        <!-- <?= $magewire->getPaymentMethod() ?> -->
    <?php endif; ?>
</div>
