<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Yireo\LokiComponents\Util\Block\CssClass;
use Yireo\LokiCheckoutMollie\Component\Checkout\Payment\Method\WithIssuer\WithIssuerViewModel;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var WithIssuerViewModel $viewModel */
/** @var CssClass $css */

$viewModel = $block->getViewModel();
?>
<ul class="<?= $css('ml-4') ?>">
    <?php foreach ($viewModel->getIssuers() as $issuer): ?>
        <li class="<?= $css('my-3', 'item') ?>">
            <label>
                <input
                    type="radio"
                    x-model="value"
                    @change="submit"
                    name="issuer"
                    value="<?= $issuer['id'] ?>"
                >
                <img class="<?= $css('mx-2 inline', 'image') ?>"
                     src="<?= $issuer['image']['svg'] ?>"
                     alt="<?= $issuer['name'] ?>">
                <?= $issuer['name'] ?>
            </label>
        </li>
    <?php endforeach; ?>
</ul>
