<?php
declare(strict_types=1);
?>
<script>
    function hideApplePayWhenNotAvailable() {
        if (!window.ApplePaySession || !window.ApplePaySession.canMakePayments()) {
            const applePayElement = document.getElementById('payment-method-option-mollie_methods_applepay');
            if (applePayElement) {
                applePayElement.parentNode.removeChild(applePayElement);
            }
        }
    }

    hideApplePayWhenNotAvailable();
</script>

