<?php
declare(strict_types=1);

/** @version 2.0.7 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    function hideApplePayWhenNotAvailable() {
        if (!window.ApplePaySession || !window.ApplePaySession.canMakePayments()) {
            const applePayElement = document.getElementById('payment-method-option-mollie_methods_applepay');
            if (applePayElement) {
                applePayElement.parentNode.removeChild(applePayElement);
            }
        }
    }

    hideApplePayWhenNotAvailable();
</script>

