<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Yireo\LokiCheckoutMollie\Component\Checkout\Payment\Method\CreditcardVault\CreditcardVaultViewModel;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var CreditcardVaultViewModel $viewModel */
?>
<div>
    <ul>
        <?php foreach ($viewModel->getNormalizedPaymentTokens() as $paymentToken): ?>
            <li>
                <label>
                    <input type="radio"
                           name="mollie_vault_public_hash"
                           :checked="isChecked"
                           @change="submitValue"
                           value="<?= $escaper->escapeHtmlAttr($paymentToken->getPublicHash()); ?>"
                    />
                    <img class="<?= $css('inline-block', '@todo') ?>"
                         loading="lazy"
                         alt="<?= $paymentToken->getType() ?>"
                         src="<?= $escaper->escapeUrl($block->getViewFileUrl('Mollie_Payment::images/creditcard-issuers/' . $paymentToken->getType() . '.svg')) ?>" />
                    <?= __('ending %1', $paymentToken->getHint()); ?>
                </label>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
