<?php
declare(strict_types=1);

use Loki\CssUtils\Util\CssClass;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use LokiCheckout\Mollie\Component\Checkout\Payment\Method\Creditcard\CreditcardViewModel;

/** @version 2.0.12 */
/** @var Escaper $escaper */
/** @var CreditcardViewModel $viewModel */
/** @var Template $block */
/** @var CssClass $css */
// @todo: Move this into XML layout instead
$fields = [
    ['card-holder', 'Card Holder', 'col-span-2'],
    ['card-number', 'Card Number', 'col-span-2'],
    ['expiry-date', 'Expiry Date', ''],
    ['verification-code', 'Verification Code', ''],
];
?>
<div class="<?= $escaper->escapeHtmlAttr($css('grid grid-cols-2 gap-4')) ?>">
    <?php foreach ($fields as $field): ?>
        <?php $fieldCode = $field[0]; ?>
        <?php $fieldLabel = $field[1]; ?>
        <?php $fieldClass = $field[2]; ?>
        <div class="<?= $escaper->escapeHtml($fieldClass) ?><?= $escaper->escapeHtmlAttr($css('', 'field')) ?>">
            <label class="<?= $escaper->escapeHtmlAttr($css('inline-block mb-1.5', 'label')) ?>">
                <?= $escaper->escapeHtml(__($fieldLabel)) ?>
            </label>

            <div id="<?= $escaper->escapeHtml($viewModel->getElementId()) ?>-<?= $escaper->escapeHtml($fieldCode) ?>" class="<?= $escaper->escapeHtmlAttr($css('', 'field-code')) ?>"></div>
            <div class="<?= $escaper->escapeHtmlAttr($css('', 'messages')) ?>">
                <div class="<?= $escaper->escapeHtmlAttr($css('error', 'message')) ?>" id="<?= $escaper->escapeHtml($viewModel->getElementId()) ?>-<?= $escaper->escapeHtml($fieldCode) ?>-error"></div>
            </div>
        </div>
    <?php endforeach; ?>

    <style>
        .mollie-component {
            height: auto !important;
        }
    </style>
</div>
