<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\LokiComponents\Util\Block\CssClass;
use Yireo\LokiCheckoutMollie\Component\Checkout\Payment\Method\Creditcard\CreditcardViewModel;

/** @var CreditcardViewModel $viewModel */
/** @var Template $block */
/** @var CssClass $css */
$fields = [
    'card-holder' => 'Card holder',
    'card-number' => 'Card Number',
    'expiry-date' => 'Expiry Date',
    'verification-code' => 'Verification Code',
];
?>
<div class="<?= $css('') ?>">
    <?php foreach ($fields as $field => $fieldLabel): ?>
        <label class="<?= $css('inline-block mb-1.5', 'label') ?>">
            <?= __($fieldLabel) ?>
        </label>

        <div id="<?= $viewModel->getElementId() ?>-<?= $field ?>"></div>
        <div class="loki-components-messages">
            <div class="error" id="<?= $viewModel->getElementId() ?>-<?= $field ?>-error"></div>
        </div>
    <?php endforeach; ?>

    <style>
        .mollie-component {
            height: auto !important;
        }
    </style>
</div>
