<?php
declare(strict_types=1);

use Loki\CssUtils\Util\CssClass;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use LokiCheckout\Mollie\Component\Checkout\Payment\Method\CreditcardVault\CreditcardVaultViewModel;

/** @version 2.0.6 */
/** @var CssClass $css */
/** @var Template $block */
/** @var Escaper $escaper */
/** @var CreditcardVaultViewModel $viewModel */
?>
<div>
    <ul>
        <?php foreach ($viewModel->getNormalizedPaymentTokens() as $paymentToken): ?>
            <li>
                <label>
                    <input type="radio"
                           name="mollie_vault_public_hash"
                           :checked="isChecked"
                           @change="submitValue"
                           value="<?= /* @noEscape */ $escaper->escapeHtmlAttr($paymentToken->getPublicHash()); ?>"
                    />
                    <img class="<?= /* @noEscape */ $css('inline-block', '@todo') ?>"
                         loading="lazy"
                         alt="<?= $escaper->escapeHtml($paymentToken->getType()) ?>"
                         src="<?= /* @noEscape */ $escaper->escapeUrl($block->getViewFileUrl('Mollie_Payment::images/creditcard-issuers/' . $paymentToken->getType() . '.svg')) ?>" />
                    <?= $escaper->escapeHtml(__('ending %1', $paymentToken->getHint())); ?>
                </label>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
