<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\LokiCheckoutMollie\Component\Checkout\Payment\Method\WithIssuer\WithIssuerViewModel;
use Yireo\LokiComponents\Factory\ViewModelFactory;
use Yireo\LokiComponents\Util\Block\CssClass;
use Yireo\LokiComponents\Util\Block\TemplateRenderer;

/** @var Template $block */
/** @var WithIssuerViewModel $viewModel */
/** @var ViewModelFactory $viewModelFactory */
/** @var TemplateRenderer $templateRenderer */
/** @var CssClass $css */

$templateRenderer = $viewModelFactory->create(TemplateRenderer::class);
?>
<div class="<?= $css('p-2', 'block') ?>">
    <?php if ($viewModel->hasIssuers()): ?>
        <?= $templateRenderer->html(
            $block,
            $viewModel->getChildTemplate(), [
            'alias' => 'issuers',
            'issuers' => $viewModel->getIssuers(),
        ]) ?>
    <?php else: ?>
        <span class="<?= $css('not-found', 'span' ) ?>"><?= __('No issuers found') ?></span>
        <!-- <?= $viewModel->getPaymentMethod() ?> -->
    <?php endif; ?>
</div>
