<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\LokiCheckout\Util\Block\CssClass;
use Yireo\LokiCheckoutMollie\Magewire\Checkout\Payment\Method\WithIssuer;

/** @var Template $block */
/** @var WithIssuer $withIssuer */
/** @var CssClass $css */
$issuers = $block->getIssuers();
?>
<ul class="mollie-issuer-list <?= $css('ml-4') ?>">
    <?php foreach ($issuers as $issuer): ?>
        <li class="mollie-issuer <?= $css('my-3', 'item') ?>">
            <label>
                <input
                    type="radio"
                    x-model="value"
                    name="issuer"
                    value="<?= $issuer['id'] ?>"
                >
                <img class="<?= $css('mx-2 inline', 'image') ?>"
                     src="<?= $issuer['image']['svg'] ?>"
                     alt="<?= $issuer['name'] ?>">
                <?= $issuer['name'] ?>
            </label>
        </li>
    <?php endforeach; ?>
</ul>
