<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Loki\Components\Factory\ViewModelFactory;
use LokiCheckout\Mollie\ViewModel\AdditionalPaymentDetails;

/** @version 2.0.9 */
/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var AdditionalPaymentDetails $additionalPaymentDetails */
$additionalPaymentDetails = $viewModelFactory->create(AdditionalPaymentDetails::class);
$html = $additionalPaymentDetails->getAdditionalHtml();

if (empty($html)) {
    return;
}
?>
<div>(<?= /* @noEscape */ $html ?>)</div>
