<script>
    document.addEventListener('alpine:init', () => {
        window.mollie = null;
        window.mollieCardComponent = null;

        Alpine.data('LokiCheckoutMollieCreditcard', () => ({
                ...LokiCheckoutComponentType,
                profileId: '',
                locale: '',
                testMode: true,
                mollieComponents: [],
                mollieCompletedComponents: [],
                initActions: {
                    ...LokiCheckoutComponentType.initActions,
                    renderMollieComponentsAnyway() {
                        setTimeout( () => {
                            this.renderMollieComponents();
                        }, 500);
                    }
                },
                createComponent(componentType, domId) {
                    if (this.mollieComponents[domId]) {
                        return;
                    }

                    const mollie = this.getMollie();
                    const component = mollie.createComponent(componentType);
                    const errorElement = document.getElementById(this.elementId + '-' + domId + '-error');

                    component.mount('#' + this.elementId + '-' + domId);
                    component.addEventListener('change', event => {
                        if (event.error && !event.touched) {
                            delete this.mollieCompletedComponents[componentType];
                            return;
                        }

                        if (event.error && event.touched) {
                            errorElement.textContent = event.error;
                            delete this.mollieCompletedComponents[componentType];
                            return true;
                        }

                        errorElement.textContent = '';

                        this.mollieCompletedComponents[componentType] = true;
                        if (Object.keys(this.mollieCompletedComponents).length === 4) {
                            this.submit();
                        }
                    });

                    this.mollieComponents[domId] = component;
                },
                getMollie() {
                    if (!window.mollie) {
                        window.mollie = Mollie(this.profileId, {
                            locale: this.locale,
                            testmode: this.testMode,
                        });
                    }

                    return window.mollie;
                },
                renderMollieComponents() {
                    this.getMollie();
                    this.createComponent('cardNumber', 'card-number');
                    this.createComponent('cardHolder', 'card-holder');
                    this.createComponent('expiryDate', 'expiry-date');
                    this.createComponent('verificationCode', 'verification-code');
                }
                ,
                async submit() {
                    const mollie = this.getMollie();

                    if (!mollie) {
                        console.log('<?= __('Mollie object unavailable') ?>');
                        return false;
                    }

                    const {token, error} = await mollie.createToken();

                    if (error) {
                        console.log('<?= __('Mollie Error') ?>', error);
                        return false;
                    }

                    if (!token) {
                        console.log('<?= __('Empty Mollie token') ?>');
                        return false;
                    }

                    this.post({token: token, render: 0});
                },
                destroyActions: {
                    ...LokiCheckoutComponentType.destroyActions,
                    unmountMollieComponents() {
                        Object.keys(this.mollieComponents).forEach((domId, component) => {
                            if (document.getElementById(domId)) {
                                component.unmount();
                            }
                        })
                        this.mollieComponents = {};
                    }
                }
            })
        );
    });
</script>
