<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LokiCheckoutMollieIssuer', () => {
            return {
                name: 'LokiCheckoutMollieIssuer',
                wireId: '',
                step: 'billing',
                value: '',
                valid: false,
                required: false,
                init() {
                    const componentData = JSON.parse(this.$el.dataset.component);
                    for (const [key, value] of Object.entries(componentData)) {
                        this[key] = value;
                    }

                    Alpine.store('components').add(this);

                    this.$watch('value', (value) => {
                        if (value) {
                            this.valid = true;
                            Magewire.find(this.wireId).saveIssuer(this.value);
                        }
                    });
                }
            }
        });
    });
</script>
