<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LokiCheckoutMollieIssuer', () => ({
            ...Object.assign({}, LokiGenericComponentType),
            afterInit() {
                this.$watch('value', (value) => {
                    if (value) {
                        this.valid = true;
                        Magewire.find(this.wireId).setValue(this.value);
                    }
                });
            }
        }));
    });
</script>
